
import "bootstrap/dist/css/bootstrap.min.css";
import './globals.css'
import { Inter } from 'next/font/google'

import Header from '@/components/layout/header'
import Footer from '@/components/layout/footer'
import Aside from '@/components/layout/aside'
import Aside2 from '@/components/layout/aside2'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
     
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="container p-0 k_tbdr">
    <Header/>
    <main>
      <div className="row h-100 m-0"> 
         <Aside/>
        {children}
        <Aside2/>
      </div>
    </main>
    <Footer/>
    </div> 
        </body>
    </html>
  )
}
